### PR TITLE
Update android compileSdkVersion to 28

### PR DESCRIPTION
**Pull request by guersam**
To resolve build error when R8 is enabled.

https://github.com/flutter/flutter/issues/27226#issuecomment-458574164

### CODE REVIEW

**Comment by j0j00** [comment]
Thanks, do you mind updating the PR to do a full AndroidX integration? Example of this being done is available [here](https://github.com/j0j00/flutter_liquidcore/commit/674d8a152b9a4820210656a967c08741430beb40).

Once you test to confirm that it doesn't break anything, I can publish the update up.

**Comment by guersam** [comment]
I'm willing to, but it won't be anytime soon due to lack of time :( Thanks for the response with a detailed example BTW!

**Comment by miguelpruivo** [comment]
Please merge this ASAP so we don't have to use a fork reference for a customer app.

**Comment by adrianvintu** [comment]
my fix, here https://github.com/adee42/flutter_keyboard_visibility/issues/42#issuecomment-566656630

**Comment by guersam** [comment]
Superseded by #8. Thanks, @yousifk!

**Pull request closed without merging**
