### PR TITLE
Update compileSdkVersion

### PR DESCRIPTION
**Pull request by miguelpruivo**
Updates `compileSdkVersion` from 27 to 28.

pubpspec.yaml and changelog were both updated as well, so it's ready to deploy a new version to pub.dev.

Thank you.

### CODE REVIEW

**Comment by miguelpruivo** [comment]
@j0j00 any news on this?

**Comment by EliuTimana** [comment]
is this package still maintained?

**Comment by miguelpruivo** [comment]
@EliuTimana I wish it was as the matter of fact that is handy and requires low maintenance.

**Comment by j0j00** [comment]
Published a [1.2.2 update](https://pub.dev/packages/flutter_user_agent) incorporating the latest changes.

Also added @miguelpruivo as a collaborator to the project, so he'll be able to handle any maintenance related tasks that might be needed in my absence.

Apologies for the delay, I wasn't receiving any notifications and last I checked #8 wasn't stable enough to merge and release.

**Comment by miguelpruivo** [comment]
Thank you @j0j00.

**Pull request merged**
